### PR TITLE
fix: `resource/cloudavenue_vm_affinity_rule` - Set more than 2VMs IDs

### LINKED ISSUE #380: [Bug]: the vm_ids  parameter of `cloudavenue_vm_affinity_rule` is limited at 2 values only
### Terraform Core Version

1.5.1

### Cloud Avenue Provider Version

0.5.2

### Affected Resource(s)

* cloudavenue_vm_affinity_rule

### Expected Behavior

Add a list of VM ids with more than 2 entries.

### Actual Behavior

If we set more than two vm_ids we have an error message.

### Relevant Error/Panic Output Snippet

```shell
terraform plan
╷
│ Error: Invalid Attribute Value
│ 
│   with cloudavenue_vm_affinity_rule.affinity-rule,
│   on affinity-rule.tf line 7, in resource "cloudavenue_vm_affinity_rule" "affinity-rule":
│    7:   vm_ids = [
│    8:     "urn:vcloud:vm:601b7f4b-a9a8-409e-bbd7-0304259e1a1a",
│    9:     "urn:vcloud:vm:cb539230-903e-41fc-a257-ecc8911aabee",
│   10:     "urn:vcloud:vm:bcad1915-5be6-45b1-9936-77833df6524d"
│   11:   ]
│ 
│ Attribute vm_ids list must contain at most 2 elements, got: 3
```

### Terraform Configuration Files
```hcl
resource "cloudavenue_vm_affinity_rule" "affinity-rule" {
  name     = "TestAffinityRule"
  polarity = "Anti-Affinity"
  enabled = true
  required = false
  vdc = local.cav_vdc
  vm_ids = [
    "urn:vcloud:vm:601b7f4b-a9a8-409e-bbd7-0304259e1a1a",
    "urn:vcloud:vm:cb539230-903e-41fc-a257-ecc8911aabee",
    "urn:vcloud:vm:bcad1915-5be6-45b1-9936-77833df6524d"
  ]
}
```

### Steps to Reproduce

Create an cloudavenue_vm_affinity_rule ressource with more than 2 vm_ids.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by azrod**
### Description of your changes

Fixes #380 

If you submit change in the provider code, please make sure to:

- [x] Write or modify examples in `examples/` directory
- [x] Write or modify acceptance tests
- [x] Run `make generate` to ensure the doc was updated properly

### How has this code been tested

```
TF_ACC=1 go test -v -count=1 -timeout 600m github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vm/vm_affinity_rule_resource_test.go
=== RUN   TestAccVmAffinityRuleResource
--- PASS: TestAccVmAffinityRuleResource (452.24s)
PASS
ok      command-line-arguments  452.903s
```

### CODE REVIEW

File: internal/provider/vm/vm_affinity_rule_schema.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ type vmAffinityRuleResourceModel struct {
 	Polarity types.String `tfsdk:"polarity"`
 	Required types.Bool   `tfsdk:"required"`
 	Enabled  types.Bool   `tfsdk:"enabled"`
-	VMIDs    types.List   `tfsdk:"vm_ids"`
+	VMIDs    types.Set    `tfsdk:"vm_ids"`
```
Comment (dmicheneau) [inline internal/provider/vm/vm_affinity_rule_schema.go:33]: ok, but why set type instead of list ?

**Review by dmicheneau — CHANGES_REQUESTED** [review]

**Review by dmicheneau — APPROVED** [review]

File: internal/provider/vm/vm_affinity_rule_schema.go (hunk 1 above)
Comment (dmicheneau) [reply internal/provider/vm/vm_affinity_rule_schema.go:33]: ok API return us a non order list

Comment (azrod) [reply internal/provider/vm/vm_affinity_rule_schema.go:33]: Because the vCD API does not return the VMIDs in the given order
